### ISSUE TITLE
Footer Background Issue on Mobile

### ISSUE THREAD

**Issue by griffindvs** [griffindvs/lasa2019#1]
On devices with a very small screen (i.e. mobile), the gray background of the footer does not extend to the bottom of the page. This is most likely due to the increased vertical space that the text takes up on mobile exceeding the height of the background. ![footer image](https://user-images.githubusercontent.com/18495025/34593169-cbb55b1e-f18e-11e7-8a09-0d1200da454c.png)

**Comment by camtheman256** [comment]
Could have to do with the static footer height set to `155px`, probably needs to more (or just not a static height? like what happens if you don't set a height?) for mobile
https://github.com/griffindvs/lasa2019/blob/8f01c347543cdf391e72eceb4096091816baa5f0/public/css/footer.css#L2

**Comment by griffindvs** [comment]
> Could have to do with the static footer height set to 155px, probably needs to more (or just not a static height? like what happens if you don't set a height?) for mobile

@camtheman256 The way I worked out to fix it (through some quick internet searching), is to use ```@media``` in the footer.css to apply different heights to different screen sizes. The fix has already been deployed to the live site, and changes with be committed to the repo now. Code used below:

```
@media screen and (max-width: 480px){
    .footer-distributed{
        height: auto;
    }

}

@media screen and (min-width: 480px){
    .footer-distributed{
        height: 155px;
    }
}
```
